In [5]:
import numpy as np
A = np.array([[4, 2], [-5, -3]])
B = np.array([[1, 2, 4], [2, -1, 3], [0, 5, 1]])

In [6]:
n = 12
A_n = A
for i in range(1, n+1):
    A_n = np.dot(A_n, A)
    print(A_n)




[[ 6  2]
 [-5 -1]]
[[ 14   6]
 [-15  -7]]
[[ 26  10]
 [-25  -9]]
[[ 54  22]
 [-55 -23]]
[[ 106   42]
 [-105  -41]]
[[ 214   86]
 [-215  -87]]
[[ 426  170]
 [-425 -169]]
[[ 854  342]
 [-855 -343]]
[[ 1706   682]
 [-1705  -681]]
[[ 3414  1366]
 [-3415 -1367]]
[[ 6826  2730]
 [-6825 -2729]]
[[ 13654   5462]
 [-13655  -5463]]


In [7]:
n = 12
B_n = B
for i in range(1, n+1):
    B_n = np.dot(B_n, B)
    print(B_n)


[[ 5 20 14]
 [ 0 20  8]
 [10  0 16]]
[[ 45  60  94]
 [ 40  20  68]
 [ 10 100  56]]
[[165 500 454]
 [ 80 400 288]
 [210 200 396]]
[[1165 2100 2614]
 [ 880 1200 1808]
 [ 610 2200 1836]]
[[ 5365 13300 13574]
 [ 3280  9600  8928]
 [ 5010  8200 10876]]
[[31965 65300 74934]
 [22480 41600 50848]
 [21410 56200 55516]]
[[162565 373300 398694]
 [105680 257600 265568]
 [133810 264200 309756]]
[[ 909165 1945300 2168854]
 [ 620880 1281600 1461088]
 [ 662210 1552200 1637596]]
[[ 4799765 10717300 11641414]
 [ 3184080  7265600  7789408]
 [ 3766610  7960200  8943036]]
[[26234365 57089300 62992374]
 [17715280 38049600 42322528]
 [19687010 44288200 47890076]]
[[140412965 310341300 339197734]
 [ 93814480 208993600 227332448]
 [108263410 234536200 259502716]]
[[ 761095565 1666473300 1831873494]
 [ 511801680 1115297600 1229571168]
 [ 577335810 1279504200 1396164956]]
