In [1]:
import numpy as np
A = np.array([[4, 2], [-5, -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [2]:
lambdas, V = np.linalg.eig(A)
V_inv = np.linalg.inv(V)
print(lambdas)
print(V)
print(V_inv)

[ 2. -1.]
[[ 0.70710678 -0.37139068]
 [-0.70710678  0.92847669]]
[[2.3570226  0.94280904]
 [1.79505494 1.79505494]]


In [3]:
Lambda = np.dot(np.dot(V_inv, A), V)
Lambda

array([[ 2.00000000e+00,  2.22044605e-16],
       [-6.66133815e-16, -1.00000000e+00]])

In [4]:
A2 = np.dot(A, A)
A2

array([[ 6,  2],
       [-5, -1]])

In [5]:
A2_1 = np.dot(np.dot(V, Lambda ** 2), V_inv)
A2_1

array([[ 6.,  2.],
       [-5., -1.]])

In [6]:
A2_2 = np.dot(np.dot(V, Lambda ** 5), V_inv)
A2_2

array([[ 54.,  22.],
       [-55., -23.]])

In [7]:
import numpy as np 
import torch
import matplotlib.pyplot as plt
B = np.array([[1, 2, 4], [2, -1, 3], [0, 5, 1]])
B

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [8]:
Blambdas, BV = np.linalg.eig(B)
BV_inv = np.linalg.inv(BV)
print(Blambdas)
print(BV)
print(BV_inv)

[-3.25599251 -1.13863631  5.39462882]
[[-0.38021672  0.80395279  0.7014215 ]
 [-0.59949826  0.23387109  0.47053617]
 [ 0.704299   -0.5467762   0.53535371]]
[[ 0.77517847 -1.64957687  0.43421523]
 [ 1.32210573 -1.41375166 -0.48964283]
 [ 0.33050771  0.72622936  0.79659036]]


In [9]:
BLambda = np.dot(np.dot(BV_inv, B), BV)
BLambda

array([[-3.25599251e+00,  2.77555756e-15,  9.99200722e-16],
       [-6.66133815e-16, -1.13863631e+00,  1.83186799e-15],
       [-8.88178420e-16, -1.33226763e-15,  5.39462882e+00]])

In [10]:
B2 = np.dot(B, B)
B2

array([[ 5, 20, 14],
       [ 0, 20,  8],
       [10,  0, 16]])

In [11]:
B2_1 = np.dot(np.dot(BV, BLambda ** 2), BV_inv)
B2_1

array([[ 5.00000000e+00,  2.00000000e+01,  1.40000000e+01],
       [-7.10542736e-15,  2.00000000e+01,  8.00000000e+00],
       [ 1.00000000e+01, -8.88178420e-15,  1.60000000e+01]])

In [12]:
B2_2 = np.dot(np.dot(BV, BLambda ** 5), BV_inv)
B2_2

array([[1165., 2100., 2614.],
       [ 880., 1200., 1808.],
       [ 610., 2200., 1836.]])