# Eigenvectors in > 2Dimensions

In [1]:
import numpy as np

import matplotlib.pyplot as plt
X = np.array([[25, 2, 9], [5, 26, -5], [3, 7, -1]])
X

array([[25,  2,  9],
       [ 5, 26, -5],
       [ 3,  7, -1]])

In [2]:
lambdas_X, V_X = np.linalg.eig(X)
V_X

array([[-0.71175736, -0.6501921 , -0.34220476],
       [-0.66652125,  0.74464056,  0.23789717],
       [-0.22170001,  0.15086635,  0.90901091]])

In [3]:
lambdas_X

array([29.67623202, 20.62117365, -0.29740567])